# Powerline style with Nord color palette
#$username\
#[@](bg:nord0 fg:nord4)\
#$hostname\

format = """
$os\
[](bg:nord2 fg:nord4)\
$directory\
[](bg:nord2 fg:nord1)\
$git_branch\
$git_status\
$git_metrics\
[](bg:nord3 fg:nord2)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$nim\
$python\
$rust\
$scala\
$aws\
$docker_context\
[](fg:nord3)\
$fill\
([](fg:nord3)$status[$username](bg:nord3 fg:nord4)[@](bg:nord3 fg:nord4)[$hostname](bg:nord3 fg:nord4)$jobs$cmd_duration)
$character
"""

#([](fg:nord3)[$status$jobs$cmd_duration](bg:nord3))
scan_timeout = 50
command_timeout = 1000
add_newline = false
palette = 'nord'

[fill]
symbol = ' '

[palettes.nord]
nord0 = '#2E3440'
nord1 = '#3B4252'
nord2 = '#434C5E'
nord3 = '#4C566A'
nord4 = '#D8DEE9'   # White
nord8 = '#88C0D0'
nord10 = '#81A1C1'
nord11 = '#BF616A'  # Red
nord12 = '#D08770'
nord13 = '#EBCB8B'  # Yellow
nord14 = '#A2BE8A'  # Green

# username, host and OS
[username]
style_root = 'bg:nord3 fg:nord11'
style_user = 'bg:nord3 fg:nord4'
format = '[$user]($style)'
show_always = true
disabled = false

[hostname]
ssh_only = false
ssh_symbol = ' '
trim_at = '.'
format = '[$hostname$ssh_symbol ]($style)'
style = 'bg:nord3 fg:nord4'
disabled = false

[os]
format = '[ $symbol ]($style)'
style = 'bg:nord4 fg:nord1'
disabled = false
# for symbols look at the end of the file

[directory]
truncation_length = 1
truncate_to_repo = true
format = '[$read_only]($read_only_style)[ $path ]($style)'
style = 'bg:nord1 fg:nord4'
read_only = ' 󰌾'
read_only_style = 'bg:nord1 fg:nord11'
truncation_symbol = ''
disabled = false
use_logical_path = true

[directory.substitutions]
'~' = ' ~'
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '
'Projects' = ' '
'Videos' = ' '

# git
[git_branch]
symbol = ''
style = 'bg:nord2 fg:nord4'
format = '[ $symbol $branch ]($style)'

[git_status]
style = 'bg:nord2 fg:nord4'
format = '[$all_status$ahead_behind ]($style)'

[git_metrics]
added_style = 'bg:nord2 fg:nord14'
deleted_style = 'bg:nord2 fg:nord11'
format = '[+$added ]($added_style)[-$deleted ]($deleted_style)'
disabled = false

# programming
[c]
symbol = ' '
detect_extensions = ['c', 'h']
style = 'bg:nord3 fg:nord10'
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = ' '
style = 'bg:nord3 fg:nord4'
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ' '
style = 'bg:nord3 fg:nord4'
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ' '
style = 'bg:nord3 fg:nord8'
format = '[ $symbol ($version) ]($style)'

[gradle]
style = 'bg:nord3 fg:nord4'
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ' '
style = 'bg:nord3 fg:nord4'
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ' '
style = 'bg:nord3 fg:nord4'
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ' '
style = 'bg:nord3 fg:nord4'
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ' '
style = 'bg:nord3 fg:nord10'
format = '[ $symbol ($version )]($style)'

[nim]
symbol = '󰆥 '
style = 'bg:nord3 fg:nord4'
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = '  '
style = 'bg:nord3 fg:nord8'
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ''
style = 'bg:nord3 fg:nord4'
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ' '
style = 'bg:nord3 fg:nord4'
format = '[ $symbol ($version) (\($virtualenv\)) ]($style)'

[rust]
symbol = ''
style = 'bg:nord3 fg:nord12'
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ' '
style = 'bg:nord3 fg:nord4'
format = '[ $symbol ($version) ]($style)'

[aws]
symbol = ' '
style = 'bg:nord3 fg:nord4'
format = '[ $symbol($profile )(\[$duration\] )]($style)'

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[ $symbol ]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = ' '
style = 'bg:nord3 fg:nord11'
number_threshold = 1
format = '[$symbol$number ]($style)'

[cmd_duration]
min_time = 500
style = 'bg:nord3 fg:nord4'
format = '[$duration ]($style)'

# status
[status]
format = '[ $symbol ]($style)'
style = "bg:nord3 bold"
symbol = '[](bg:nord3 fg:nord11)'
success_symbol = '[](bg:nord3 fg:nord14)'
not_executable_symbol = '[🛇](bg:nord3 fg:nord11)'
not_found_symbol = '[󰍉](bg:nord3 fg:nord11)'
sigint_symbol = '[](bg:nord3 fg:nord13)'
signal_symbol = '[](bg:nord3 fg:nord11)'
disabled = false

# OS symbols
[os.symbols]
Alpaquita = ' '
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '󰛓 '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = '󰈸 '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = '󰈺 '
openSUSE = ' '
OracleLinux = '󰌷 '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
Redox = '󰀘 '
Solus = '󰠳 '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Windows = '󰍲 '

