exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = uwsm-app -- elephant
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- hyprpolkitagent
exec-once = uwsm-app -- mako
exec-once = uwsm-app -- swayosd-watchdog
exec-once = uwsm-app -- walker --gapplication-service
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- wl-paste --watch cliphist store
